module.exports = [
    {
        name: "Echo Dot 5th Gen",
        title: "Echo Dot (5th Gen, 2022 release) | Smart speaker with Alexa | Charcoal",
        brand: "Amazon",
        category: "Tech",
        description: "<h3>Our best-sounding Echo Dot yet</h3><p>Enjoy an improved audio experience compared to any previous Echo Dot with Alexa for clearer vocals, deeper bass and vibrant sound in any room.</p><ul><li><strong>Your favorite music and content:</strong> Play music, audiobooks, and podcasts from Amazon Music, Apple Music, Spotify and others.</li><li><strong>Alexa is ready to help:</strong> Ask Alexa for weather updates and to set hands-free timers, get answers to your questions and even hear jokes.</li></ul>",
        imageDescription: "A small, spherical smart speaker in dark charcoal fabric with a glowing blue light ring around the base.",
        bulletPoints: ["Improved audio experience", "Voice control your smart home", "Designed to protect your privacy"],
        price: 49.99,
        subcategory: "Smart Home",
        image: "https://images.unsplash.com/photo-1543512214-318c7553f230?w=500&q=80",
        images: ["https://images.unsplash.com/photo-1543512214-318c7553f230?w=800&q=80"],
        stock: 250,
        attributes: { "Color": "Charcoal", "Connectivity": "Wi-Fi, Bluetooth" },
        aiTags: ["smart speaker", "alexa", "home assistant", "audio", "voice control", "amazon echo"],
        specifications: [{ key: "Dimensions", value: "3.9 x 3.9 x 3.5 in" }, { key: "Weight", value: "304g" }]
    },
    {
        name: "MacBook Air M2",
        title: "Apple 2022 MacBook Air Laptop with M2 chip: 13.6-inch Liquid Retina Display",
        brand: "Apple",
        category: "Tech",
        description: "<h3>Supercharged by M2</h3><p>The redesigned MacBook Air is more portable than ever and weighs just 2.7 pounds. It’s the incredibly capable laptop that lets you work, play or create just about anything — anywhere.</p><ul><li><strong>Strikingly thin design:</strong> The redesigned MacBook Air is more portable than ever.</li><li><strong>Supercharged by M2:</strong> Get more done faster with a next-generation 8-core CPU, up to 10-core GPU and up to 24GB of unified memory.</li></ul>",
        imageDescription: "A sleek, incredibly thin silver laptop partially opened, showcasing a vibrant display.",
        bulletPoints: ["13.6-inch Liquid Retina display", "M2 chip with 8-core CPU", "18 hours of battery life"],
        price: 1099.00,
        subcategory: "Laptops",
        image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500&q=80",
        images: ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80"],
        stock: 45,
        attributes: { "Color": "Silver", "RAM": "8GB", "Storage": "256GB SSD" },
        aiTags: ["laptop", "apple", "macbook", "m2", "computer", "productivity", "retina"],
        specifications: [{ key: "Screen Size", value: "13.6 Inches" }, { key: "CPU", value: "Apple M2" }]
    },
    {
        name: "Sony WH-1000XM5",
        title: "Sony WH-1000XM5 Wireless Noise Canceling Headphones",
        brand: "Sony",
        category: "Tech",
        description: "<h3>Industry-leading noise cancellation</h3><p>Two processors control 8 microphones for unprecedented noise cancellation. With Auto NC Optimizer, noise canceling is automatically optimized based on your wearing conditions and environment.</p><ul><li><strong>Magnificent Sound:</strong> Engineered to perfection with the new Integrated Processor V1.</li><li><strong>Crystal clear hands-free calling:</strong> 4 beamforming microphones, precise voice pickup.</li></ul>",
        imageDescription: "Premium over-ear wireless headphones with a matte black finish and sleek, minimal headband.",
        bulletPoints: ["Industry-leading noise cancellation", "Up to 30-hour battery life", "Touch sensor controls"],
        price: 348.00,
        subcategory: "Audio",
        image: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=500&q=80",
        images: ["https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800&q=80"],
        stock: 120,
        attributes: { "Color": "Black", "Form Factor": "Over Ear" },
        aiTags: ["headphones", "wireless", "noise canceling", "audio", "sony", "music"],
        specifications: [{ key: "Battery Life", value: "30 Hours" }, { key: "Bluetooth", value: "5.2" }]
    },
    {
        name: "Logitech MX Master 3S",
        title: "Logitech MX Master 3S - Wireless Performance Mouse",
        brand: "Logitech",
        category: "Tech",
        description: "<h3>An icon remastered</h3><p>Meet MX Master 3S – an iconic mouse remastered. Feel every moment of your workflow with even more precision, tactility, and performance, thanks to Quiet Clicks and an 8,000 DPI track-on-glass sensor.</p><ul><li><strong>Quiet Clicks:</strong> Deliver satisfying tactile feel with 90% less click noise.</li><li><strong>MagSpeed Scrolling:</strong> A computer mouse with remarkable speed, precision, and near silence.</li></ul>",
        imageDescription: "An ergonomic right-handed wireless mouse in graphite grey with a thumb rest and metal scroll wheel.",
        bulletPoints: ["8000 DPI, Track on glass", "Quiet Clicks", "USB-C Rechargeable"],
        price: 99.99,
        subcategory: "Accessories",
        image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=800&q=80"],
        stock: 300,
        attributes: { "Color": "Graphite", "Connectivity": "Bluetooth, Logi Bolt" },
        aiTags: ["mouse", "wireless", "ergonomic", "productivity", "logitech", "accessories"],
        specifications: [{ key: "Sensor", value: "8000 DPI" }, { key: "Battery", value: "70 days on full charge" }]
    }
];
